version: '3.8'
services:
  app-postgres:
    container_name: postgres-container
    image: "postgres"
    networks:
      - user-netwoks
    hostname: app-postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    volumes:
      - pg_data:/var/lib/postgresql/data

  tomcat:
    build: ./docker/tomcat
    container_name: tomcat-container
    networks:
      - user-netwoks
    hostname: app-tomcat
    depends_on:
      - app-postgres
    ports:
      - "8080:8080"
  web:
    container_name: nginx-web1
    build: ./docker/nginx1
    depends_on:
      - tomcat
    networks:
      - user-netwoks
    hostname: app-web1
    ports:
      - 7080:7080
  web1:
    container_name: nginx-web2
    build: ./docker/nginx2
    depends_on:
      - tomcat
    networks:
      - user-netwoks
    hostname: app-web2
    ports:
      - 7000:7000
  web-client:
    container_name: nginx-web-client
    build: ./docker/nginx-web
    depends_on:
      - tomcat
      - web
      - web1
    networks:
      - user-netwoks
    hostname: app-web-client
    ports:
      - 8000:8000
networks:
  user-netwoks:
volumes:
  pg_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./datapg